kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-provisioner
  namespace: testns
spec:
  selector:
    matchLabels:
      app: efs-provisioner
      namespace: testns
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
        namespace: testns
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              value: fs-1765efc6
            - name: AWS_REGION
              value: ap-south-1
            - name: PROVISIONER_NAME
              value: mytest/aws-efs
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-1765efc6.efs.ap-south-1.amazonaws.com
            path: /
