apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: ap-south-1

nodeGroups:
  - name: eksng-A
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      publicKeyName: key2
  - name: eksng-B
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      publicKeyName: key2